//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblInvoice = new HashSet<tblInvoice>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> ProID { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string PayMethod { get; set; }
        public Nullable<int> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInvoice> tblInvoice { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
